stages:
  # Data Ingestion Stage: Downloads and saves raw data
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  # Data Preprocessing Stage: Cleans and normalizes the data
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/data/data_preprocessing.py
    outs:
    - data/interim  

  # Model Building Stage: Trains the LightGBM model
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/interim/train_preprocessed.csv
    - src/model/model_building.py
    params:
    - model_building.max_features
    - model_building.ngram_range
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl

  # Model Evaluation Stage: Evaluates the model and logs metrics to MLflow
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - data/interim/train_preprocessed.csv
    - data/interim/test_preprocessed.csv
    - src/model/model_evaluation.py
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl
    outs:
    - experiment_info.json

  # Model Registration Stage: Registers the model to MLflow Model Registry
  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - experiment_info.json
    - src/model/register_model.py